server.port=8080

# å­ç¬¦ç¼ç éç½®
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# SSEååºçé»è®¤å­ç¬¦ç¼ç 
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true

logging.level.root=INFO
logging.level.com.example.demo=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.core.task=DEBUG
logging.level.org.springframework.scheduling.concurrent=DEBUG